@LiL.TimeTracking_HostAddress = https://localhost:7228

GET {{LiL.TimeTracking_HostAddress}}/weatherforecast/
Accept: application/json

###

# Employee Requests

GET {{LiL.TimeTracking_HostAddress}}/api/Employee
Accept: application/json 

###

GET {{LiL.TimeTracking_HostAddress}}/api/Employee/1
Accept: application/json 

###

POST {{LiL.TimeTracking_HostAddress}}/api/Employee
Content-Type:application/json 

{
    "Name":"Employee 3",
    "StartDate": "2019-02-02"
}
###

PUT {{LiL.TimeTracking_HostAddress}}/api/Employee/2
Content-Type:application/json 

{
    "Id":2,
    "Name":"Employee 2 (updated)",
    "StartDate": "2020-04-12"
}
###

PATCH {{LiL.TimeTracking_HostAddress}}/api/Employee/2
Content-Type:application/json 

[
    {
        "op":"add",
        "path":"/name",
        "value":"Employee 2 (patched)"
    }
]

###

DELETE {{LiL.TimeTracking_HostAddress}}/api/Employee/3

###

GET {{LiL.TimeTracking_HostAddress}}/api/Employee/1/Projects
Accept: application/json

###

#Project Requests
GET {{LiL.TimeTracking_HostAddress}}/api/Project
Accept: application/json

###

GET {{LiL.TimeTracking_HostAddress}}/api/Project/1
Accept: application/json

###

POST {{LiL.TimeTracking_HostAddress}}/api/Project
Accept: application/json 
Content-Type: application/json

{
    "Name":"Big Project",
    "StartDate": "2023-08-01"
}
###

POST {{LiL.TimeTracking_HostAddress}}/api/Project
Accept: application/json 
Content-Type: application/json

{
    "Name":"Small Project",
    "StartDate": "2024-01-01",
    "EndDate":"2024-06-01"
}
###

PUT {{LiL.TimeTracking_HostAddress}}/api/Project/2
Accept: application/json 
Content-Type: application/json

{
    "Id":2,
    "Name":"Small Project",
    "StartDate": "2024-01-01",
    "EndDate":"2024-05-01"
}
###

DELETE {{LiL.TimeTracking_HostAddress}}/api/Project/2

###




# Project Assignment Requests

POST {{LiL.TimeTracking_HostAddress}}/api/ProjectAssignment
Content-Type:application/json

{
    "EmployeeId":1,
    "ProjectId": 1
}

###

GET {{LiL.TimeTracking_HostAddress}}/api/ProjectAssignment
Accept: application/json

###

# Time Entry Requests

POST {{LiL.TimeTracking_HostAddress}}/api/TimeEntry
Content-Type: application/json

{
    "EmployeeId":1,
    "ProjectId":1,
    "DateWorked":"2024-03-02",
    "HoursWorked":7.75
}

###

GET {{LiL.TimeTracking_HostAddress}}/api/TimeEntry
Accept: application/json

###
