@LiL.TimeTracking_HostAddress = https://localhost:7228

GET {{LiL.TimeTracking_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{LiL.TimeTracking_HostAddress}}/api/Employee
Accept: application/json 

###

GET {{LiL.TimeTracking_HostAddress}}/api/Employee/1
Accept: application/json 

###