@LiL.TimeTracking_HostAddress = https://localhost:7228

GET {{LiL.TimeTracking_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{LiL.TimeTracking_HostAddress}}/api/Employee
Accept: application/json 

###

GET {{LiL.TimeTracking_HostAddress}}/api/Employee/1
Accept: application/json 

###

POST {{LiL.TimeTracking_HostAddress}}/api/Employee
Content-Type:application/json 

{
    "Name":"Employee 2",
    "StartDate": "2020-03-12"
}
###

PUT {{LiL.TimeTracking_HostAddress}}/api/Employee/2
Content-Type:application/json 

{
    "Id":2,
    "Name":"Employee 2 (updated)",
    "StartDate": "2020-04-12"
}
###

PATCH {{LiL.TimeTracking_HostAddress}}/api/Employee/2
Content-Type:application/json 

[
    {
        "op":"add",
        "path":"/name",
        "value":"Employee 2 (patched)"
    }
]

###